- name: Check debconf for mariadb-server entries
  shell: (debconf-get-selections | grep -q -s mariadb-server); echo $?
  register: debconf
  ignore_errors: yes

- name: Set debconf mariadb-server root password
  debconf: name=mariadb-server question="mariadb-server/root_password" value="{{ idp_rdbms_pw }}" vtype="password"
  when: debconf.stdout == "1"
    
- name: Set debconf mariadb-server root password again
  debconf: name=mariadb-server question="mariadb-server/root_password_again" value="{{ idp_rdbms_pw }}" vtype="password"
  when: debconf.stdout == "1"

- name: Install mariadb-server
  apt: name=mariadb-server state=present

- name: Run mariadb-server
  service: name=mariadb state=started enabled=yes

- name: upload sql datatabse
  template: 
    src: roles/{{ role_name }}/templates/shibboleth.sql
    dest: "{{ tmp_upload_dir }}/shibboleth.sql"

- name: Create Shibboleth Database
  shell: "mariadb -u root < {{ tmp_upload_dir }}/shibboleth.sql"
  # shell: "mariadb -u root --password={{ idp_rdbms_pw }} < {{ tmp_upload_dir }}/shibboleth.sql"

- name: Remove temporary SQL dump
  file: path="{{ tmp_upload_dir }}/shibboleth.sql" state=absent

- name: Check table RuoliOrganizzativi
  shell: "echo 'SELECT * FROM RuoliOrganizzativi' | mariadb -u {{ idp_rdbms_user }} --password={{ idp_rdbms_pw }} {{ idp_rdbms_dbname }}"
  register: ruoli_org

- name: Copy temporary insert-ruoliorganizzativi.sql
  copy:
    src: roles/{{ role_name }}/files/insert-ruoliorganizzativi.sql
    dest: "{{ tmp_upload_dir }}/insert-ruoliorganizzativi.sql"

- name: Load table RuoliOrganizzativi
  shell: "mariadb -u root {{ idp_rdbms_dbname }} < {{ tmp_upload_dir }}/insert-ruoliorganizzativi.sql"
  # shell: "mariadb -u root --password={{ idp_rdbms_pw }} {{ idp_rdbms_dbname }} < {{ tmp_upload_dir }}/insert-ruoliorganizzativi.sql"
  when: ruoli_org.stdout == ""

- name: Clean temporary insert-ruoliorganizzativi.sql
  file:
    state: absent
    path: "{{ tmp_upload_dir }}/insert-ruoliorganizzativi.sql"

- name: Check table user_orcid
  shell: "echo 'SELECT * FROM user_orcid' | mariadb -u {{ idp_rdbms_user }} --password={{ idp_rdbms_pw }} {{ idp_rdbms_dbname }}"
  register: ruoli_org

- name: Copy temporary insert-userorcid.sql
  copy:
    src: roles/{{ role_name }}/files/insert-userorcid.sql
    dest: "{{ tmp_upload_dir }}/insert-userorcid.sql"

- name: Load table user_orcid
  shell: "mariadb -u root {{ idp_rdbms_dbname }} < {{ tmp_upload_dir }}/insert-userorcid.sql"
  # shell: "mariadb -u root --password={{ idp_rdbms_pw }} {{ idp_rdbms_dbname }} < {{ tmp_upload_dir }}/insert-userorcid.sql"
  when: ruoli_org.stdout == ""

- name: Clean temporary insert-userorcid.sql
  file:
    state: absent
    path: "{{ tmp_upload_dir }}/insert-userorcid.sql"
