- name: Configure global.xml (dataStore and persistentId)
  template:
    src: roles/{{ role_name }}/templates/global.xml
    dest:  "{{ idp_path }}/conf/global.xml"
    backup: yes

# Remove the comment to the bean called "c14n/SAML2Persistent"
# - name: Configure subject-c14n.xml (persistentId)
  # copy:
    # src: roles/{{ role_name }}/files/subject-c14n.xml
    # dest:  "{{ idp_path }}/conf/c14n/subject-c14n.xml"
    # backup: yes

- replace:
    path: "{{ idp_path }}/conf/saml-nameid.properties"
    regexp: '#idp.persistentId.generator = shibboleth.StoredPersistentIdGenerator'
    replace: 'idp.persistentId.generator = shibboleth.StoredPersistentIdGenerator'
    backup: yes

- replace:
    path: "{{ idp_path }}/conf/saml-nameid.properties"
    regexp: '#idp.persistentId.dataSource = shibboleth.JPAStorageService.DataSource'
    replace: 'idp.persistentId.dataSource = shibboleth.JPAStorageService.DataSource'
    backup: yes

- replace:
    path: "{{ idp_path }}/conf/saml-nameid.properties"
    regexp: '#idp.persistentId.computed = shibboleth.ComputedPersistentIdGenerator'
    replace: 'idp.persistentId.computed = shibboleth.ComputedPersistentIdGenerator'
    backup: yes

#  SAML2PersistentGenerator on RDBMS
- replace:
    path: "{{ idp_path }}/conf/idp.properties"
    regexp: '#idp.session.StorageService = shibboleth.ClientSessionStorageService'
    replace: 'idp.session.StorageService = shibboleth.JPAStorageService'
    backup: yes

- replace:
    path: "{{ idp_path }}/conf/idp.properties"
    regexp: '#idp.consent.StorageService = shibboleth.ClientPersistentStorageService'
    replace: 'idp.consent.StorageService = shibboleth.JPAStorageService'

- replace:
    path: "{{ idp_path }}/conf/idp.properties"
    regexp: '#idp.replayCache.StorageService = shibboleth.StorageService'
    replace: 'idp.replayCache.StorageService = shibboleth.JPAStorageService'

- replace:
    path: "{{ idp_path }}/conf/idp.properties"
    regexp: '#idp.replayCache.StorageService = shibboleth.StorageService'
    replace: 'idp.replayCache.StorageService = shibboleth.JPAStorageService'

- replace:
    path: "{{ idp_path }}/conf/idp.properties"
    regexp: '#idp.artifact.StorageService = shibboleth.StorageService'
    replace: 'idp.artifact.StorageService = shibboleth.JPAStorageService'

- replace:
    path: "{{ idp_path }}/conf/idp.properties"
    regexp: '#idp.artifact.StorageService = shibboleth.StorageService'
    replace: 'idp.artifact.StorageService = shibboleth.JPAStorageService'
