# METADATAS - SP
# reboot time (thank you servlet_container) makes metadata GET fails or return 404!
# Marco Malavolti consiglia una regexp sul log di avvio di tomcat/jetty relativo all'idp, funziona bene!
- name: "Wait until the string 'RemoteUserAuthServlet will process REMOTE_USER' appears in {{ idp_path }}/logs/idp-process.log"
  wait_for:
    path: "{{ idp_path }}/logs/idp-process.log"
    search_regex: "RemoteUserAuthServlet will process REMOTE_USER"
  when: servlet_container == "tomcat"

- name: Configure IdP attribute-filter-local.xml
  template:
    src: roles/shib3idp_configure/templates/attribute-filter-local.xml
    dest: "{{ idp_path }}/conf/attribute-filter-local.xml"
    # backup: yes

- replace:
    path: "{{ idp_path }}/conf/services.xml"
    regexp: '<value>%{idp.home}/conf/attribute-filter.xml</value>'
    replace: '<value>%{idp.home}/conf/attribute-filter.xml</value>\n
              \t<value>%{idp.home}/conf/attribute-filter-local.xml</value>'
    backup: yes

# the old one
# - name: sleep for 10 seconds to let servlet reboot and make its bootstrap assessments
  # wait_for: timeout=10

- name: Add IdP Metadata to SP (/etc/shibboleth/metadata/{{ idp_fqdn }}-metadata.xml)
  get_url:
    url: "{{ idp_entity_id }}"
    dest: "/etc/shibboleth/metadata/{{ idp_fqdn }}-metadata.xml"
    validate_certs: no
    force: yes
    timeout: 60

- name: Restart shibd
  service: name=shibd state=restarted enabled=yes

- name: Register SP into Shibboleth IdP's metadata-providers.xml
  template:
    src: roles/{{ role_name }}/templates/metadata-providers.xml
    dest: "{{ idp_path }}/conf/metadata-providers.xml"
    backup: yes

- name: Add SP {{ sp_fqdn }} Metadata to Shibboleth IdP
  get_url:
    url: https://{{ sp_fqdn }}/Shibboleth.sso/Metadata
    dest: "{{ idp_path }}/metadata/{{ sp_fqdn }}-metadata.xml"
    validate_certs: no
    force: yes

- name: Restart Jetty
  service: name="jetty" state=restarted enabled=yes
  when: servlet_container == "jetty"

- name: Restart Tomcat
  service: name="{{ tomcat_version }}" state=restarted enabled=yes
  when: servlet_container == "tomcat"

- name: Update GIT repository with a branch for this kind of federation
  shell: "cd {{ idp_path }} && git checkout -b federation && git add -A && git commit -am 'Shibboleth SP federated'"
